version: '3.3'
services:
  bot:
    build: .
    command: sh -c "python -m bot"
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - todo-sqlite-data:/database/

  sqlite3:
    image: sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - todo-sqlite-data:/root/db/