version: '3.3'
services:
  bot:
    build: .
    command: sh -c "python -m bot"
    restart: always
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./databases:/root/databases/

#  sqlite3:
#    image: nouchka/sqlite3:latest
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./databases:/root/databases/
